version: 2.1

commands:
  print_pipeline_id:
    description: "A command that prints the Circle CI Workflow ID from its environment variable"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  print_pipeline_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
        name: fail
        command: return 1
        when: on_fail

workflows:
  my_workflow:
    jobs:
      - print_pipeline_id
